export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SELECTED_PRODUCT = 'SELECTED_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SET_ISLOADING = 'SET_ISLOADING';
export const SET_LOGIN = 'SET_LOGIN'
export const SET_LOGOUT = 'SET_LOGOUT'